name: folio
description: "Folio – The Offline Document Studio"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  provider: ^6.1.2
  equatable: ^3.0.0
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  path: ^1.9.1
  image_picker: ^1.2.3
  google_mlkit_text_recognition: ^0.17.1
  pdf: ^3.13.0
  open_filex: ^4.7.0
  signature: ^6.4.0
  intl: ^0.20.3
  google_fonts: ^8.2.1
  share_plus: ^13.3.0
  file_picker: ^13.1.0
  image_cropper: ^12.2.1

dependency_overrides:
  material_color_utilities: 0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
